### ISSUE TITLE
Hyper-tuning update

### ISSUE THREAD

**Issue by zhujiem** [reczoo/FuxiCTR#118]
```
base_config: ../model_zoo/DCN/DCN_torch/config/
base_expid: DCN_default
dataset_id: tiny_npz

tiny_npz:
    data_root: ../data/
    data_format: npz
    train_data: ../data/tiny_npz/train.npz
    valid_data: ../data/tiny_npz/valid.npz
    test_data: ../data/tiny_npz/test.npz

tuner_space:
    model_root: './checkpoints/'
    embedding_dim: 16
    dnn_hidden_units: [[1024, 512, 256]]
    num_cross_layers: [5, 4]
    embedding_regularizer: [1.e-4, 5.e-4, 1.e-3, 5.e-3]
    net_dropout: [0.2, 0.1, 0]
    batch_norm: False
    learning_rate: 5.e-4
    batch_size: 1024
    seed: 20222023
    group_id: user_id
    metrics: [[gAUC, AUC, logloss]]
    monitor: {"gAUC": 1, "AUC": 1}
```
